version: '3'
services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/go:cached
    tty: true
    stdin_open: true
